version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ecommerce_be
      POSTGRES_PASSWORD: "_rnxPZkXQX75d0lWGR16kDNiiZLTTmTU"
    volumes:
      - ecommerce_be_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "Eo2gyunaGw7kDPDo-4NUVRCJQcHSt65K"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  ecommerce_be_data:
